[package]
name = "tardis-example-pg-graph_search"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
tardis = { path = "../../tardis", features = ["reldb", "test"] }
