[package]
name = "tardis-example-multi-apps-doc"
version = "0.1.0"
authors = ["gudaoxuri"]
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
tardis = { path = "../../../tardis", features = ["reldb", "web-server"] }
