[package]
name = "tardis-example-reldb"
version = "0.1.0"
authors = ["gudaoxuri"]
edition = "2021"

[dependencies]
tardis = { path = "../..", features = ["reldb", "test"] }
sea-orm = { version = "^0.8", features = ["macros"] }
