[package]
name = "tardis-example-todos"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
# Tardis Functions
tardis = { path = "../../tardis", features = ["web-server", "reldb", "test"] }
