[package]
name = "tardis-example-perf-test"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
# Tardis Functions
tardis = { path = "../../tardis", features = ["web-server", "reldb"] }
