[package]
name = "tardis-example-websocket"
version = "0.1.0"
authors = ["gudaoxuri"]
edition = "2021"

[dependencies]
futures-util = { version = "^0.3" }
tardis = { path = "../..", features = ["web-server"] }
poem = { version = "^1.3" }
poem-openapi = { version = "^2" }