[package]
name = "tardis-example-websocket"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
tardis = { path = "../../tardis", features = ["web-server"] }
