[package]
name = "tardis-example-web-basic"
version = "0.1.0"
authors = ["gudaoxuri"]
edition = "2021"

[dependencies]
tardis = { path = "../..", features = ["web-server"] }
poem-openapi = { version = "^2" }

