[package]
name = "tardis-example-web-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
tardis = { path = "../../tardis", features = ["web-client"] }