name: CICD

on: [ push ]

env:
  TARDIS_TEST_DISABLED_DOCKER: true

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        options: -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=test
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      rabbit:
        image: rabbitmq:management
        ports:
          - 15672:15672
          - 25672:25672
          - 5671:5671
          - 5672:5672
          - 4369:4369
        options: -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest
      es:
        image: elasticsearch:8.1.0
        ports:
          - 9200:9200
        options: -e ELASTIC_PASSWORD=123456 -e discovery.type=single-node
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init rust envrionment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache rust
        uses: Swatinem/rust-cache@v1

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check with clippy
        run: cargo clippy --all-features

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.19.1'
          args: '--all-features'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: cobertura.xml

  check-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init rust envrionment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache rust
        uses: Swatinem/rust-cache@v1

      - name: Check format
        run: cargo fmt --all -- --check
        working-directory: examples

      - name: Check with clippy
        run: cargo clippy
        working-directory: examples

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [check, check-examples]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init rust envrionment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_TOKEN }}

      - name: Cargo package
        run: cargo package

      - name: Cargo publish
        run: cargo publish
